syntax = "All"
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "ForceDouble"
call_parentheses = "Always"
space_after_function_names = "Never"
block_newline_gaps = "Never"
collapse_simple_statement = "Never"
